#!/usr/bin/env python3

import argparse
import logging

from xtool.configuration import ConfigManager
from xtool.execution import ExecEnvironment
from xtool.instances import InstanceManager
from xtool.versions import VersionManager

from xtool.utils import init_logger
from xtool.utils import parse_args

args = parse_args()
init_logger(args.verbose)
logger = logging.getLogger('Main')

cm = ConfigManager()
vm = VersionManager(cm)
im = InstanceManager(cm, vm)
ex = ExecEnvironment()

logger.debug('Arguments : {}'.format(args))
if ('list'.startswith(args.action)):
    if ('versions'.startswith(args.entity)):
      print(cm.versions())
    elif ('instances'.startswith(args.entity)):
      print(cm.instances())
elif ('download'.startswith(args.action)):
    vm.download(args.version)
elif ('create'.startswith(args.action)):
    im.create(args.instance_name, args.version)
elif ('start'.startswith(args.action)):
    # Check if we have an explicit instance name, else, use the environment
    if args.instance_name:
        im.start(args.instance_name, args.debug)
    elif ex.getInferredInstanceName():
        im.start(ex.getInferredInstanceName(), args.debug)
    else:
        logger.error('Unable to determine the name of the instance to start.')
elif ('remove'.startswith(args.action)):
    im.remove(args.instance_name)
